name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Roda automaticamente todo dia à meia-noite
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Dev-Phap
          outputs: github-contribution-grid-snake.svg

      - name: Commit e Push dos arquivos gerados
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add github-contribution-grid-snake.svg
          git commit -m "Atualizando animação da cobrinha" || echo "Nenhuma mudança para commit"
          git push
