name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite UTC

  workflow_dispatch:  # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Dev-Phap  # Substitua pelo seu usuário do GitHub
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg

      - name: Enviar para o repositório
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: github-contribution-grid-snake*.svg
