name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Gerar animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: Dev-Phap
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Upload dos arquivos gerados
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: snake-animations
          path: dist

      - name: Commit e Push das mudanças
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
